# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: wsl-pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - script: |
#     echo "Logging into AWS..."
#     aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
#     aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
#     aws configure set default.region $(AWS_REGION)
#   displayName: 'Login to AWS'

# - script: |
#     aws ecr create-repository --repository-name docker-nginx
#   displayName: 'Creating the repository in AWS ECR'

- script: |
    git clone git@github.com:tol8901/$(repoName).git && cd $(repoName)
    echo "The current location and the content of the current directory:"
    pwd
    ls -lA
  displayName: 'Cloning the git repository, and going into the repository directory'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Installing Docker'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Building the image'